### ISSUE TITLE
Issue #1 Hai! Everyone, welcome to this year's code! FIRST Steamworks!

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2017#1]
We are currently making a six wheels tank drive robot with gear delivering and climbing mechanism.. (We might have a shooting part later) 
Drive base will be six wheel tank drive: This is very similar to the rookie robot we worked on for the past few weeks, look back into the code and it might be very helpful. (It is.)
Climbing: As far as I know, all our code on our git hub don't contain anything related to a shooter.
Shooting: My guess is that we will use vision tracking for this, (no matter we are doing a fixed shooter or a moving shooter) , if interested or need help, go back at look at Atilla's code. NRGRobot2016 
You can always ask for help from leadership and mentors
For now, this is all the information I have, until next time, Peace

Chuwei Guo
"The cake is a lie"---chell
Oh rite! Chell never open her mouth.

**Comment by EndenDragon** [comment]
one question, y r u sayin dis in public? wont the other teams know wat we r doin?

**Comment by gregoryquick** [comment]
@EndenDragon Because it is it really does not matter to much if other teams know what we are doing as they will see at the competitions, though we should probably have this in the readme and not a random issue...
