### ISSUE TITLE
Create the Drive subsystems!

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2017#10]
So, we have a robot, what's the most important function of a robot? It gotta be moving! Currently, we don't have a drive subsystem. So what should we do? We create one! So it is your holy task, to create a drive subsystem for our NRGRobot2017.
Please assign yourself to this issue to let others know.
Chuwei Guo
P.S.: I didn't tell you this but since our rookie bot has the exact same drive base as the drive base we plan to have this year, looking into the rookie robot's code would be very helpful. ;)

**Comment by Knayam7** [comment]
Very helpful indeed
