### ISSUE TITLE
If you want to study about vision tracking, click me. *Click bait not intended."

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2017#18]
Vision processing is very important for the robot in auto period.
Here are a few links that would be helpful:
Vision processing in general: 
https://wpilib.screenstepslive.com/s/4485/m/24194
About the camera we are using this year and how to put it on the smart dashboard:
https://wpilib.screenstepslive.com/s/4485/m/24194/l/288981-using-the-microsoft-lifecam-hd-3000

**Comment by gregoryquick** [comment]
Should this be an issue? It looks more suited for being placed in the readme...
P.S. Don't look at last years code for this; It is horrible.

**Comment by avigloz** [comment]
is this issue still relevant?
