### ISSUE TITLE
Ask a veteran about the subsystems we use

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#19]
Ask a veteran (politely) about our subsystems and have them explain what each of them do. Once you're done, have them comment on this issue and confirm your education

**Comment by ChuweyBar** [comment]
Take note that Chuwei takes light use of joking around*
XDD
Chuwei Guo

**Comment by Knayam7** [comment]
Mayank can confirm Chuwei knows about our robot subsystems :+1:
