### ISSUE TITLE
Create a readme for the Repository

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#2]
Create an overview of the repository for everyone by editing our readme file. Please include an overview of this year's challenge, Leadership, how to install Java plugins and also how to clone the repository. Before you push it out, please have a member of Programming Leadership look it over.

**Comment by Tejas2Rangole** [comment]
Mayank approved

- Chuwei's muffin

**Comment by avigloz** [comment]
Why is this so difficult to complete...
