### ISSUE TITLE
Research the use of third-party libraries for robot use

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#20]
I need someone to research third-party libraries we might use for this year's code and see if we need to install more to accommodate the sensors and equipment we use. I want a one page Word doc attached to the comment when you end the issue that tells me what we can use

Link for infor on topic: https://wpilib.screenstepslive.com/s/4485/m/13809

**Comment by chandrap2** [comment]
The plugins for [the navX gyro](http://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/) and [Talon motor controllers](http://www.ctr-electronics.com/control-system/hro.html#product_tabs_technical_resources) are third-party.

Talons:
![Uploading asd.PNG…]()
