### ISSUE TITLE
Research a scouting app for Strategy

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#21]
Ask Mayank for details, but you need to get a Strategy tablet from the Mech portable, power it up and install an apk from this site (http://cat5scouting.mobi/)

Once installation is complete, please test the app and see if it works. Look for any problems or bugs and document them. Comment on this issue when you're done and tell Reese, our Coach, if the app worked or not

**Comment by ChuweyBar** [comment]
After trying to install the .apk on several devices, we came to the conclusion that the .apk file is either corrupted or that the download path for the file is not giving the downloader the whole .apk file.
I already send an email to the team 3489 (the team who made the open sourced app) would probably get a response after weekend.
Chuwei Guo
