### ISSUE TITLE
Install the FRC Plugins

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#3]
Everyone, please install the FRC plugins 
Link here: http://wpilib.screenstepslive.com/s/4485/m/13503/l/599679-installing-eclipse-c-java
Scroll to the bottom for plugin instructions

**Comment by ChuweyBar** [comment]
If you are using the BSD network to download the plug in, do not go to option one, install online. Go to option two instead. Click the link under option two and the eclipse plugin for 2017. Then follow the steps after.

Chuwei Guo
