### ISSUE TITLE
Problem with Gear shifting!

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2017#33]
We just tested the robot, while shifting the gear, we found out that while driving and shifting gear, only one side of the robot is shifted into high gear, while the other side is still in low gear, meaning that the robot is going to turn toward one side and start to go in circles. Look into the code and identify the issue,
if(knowsToFix == true)
{
 FIX it.
}
else
{
 Tell someone Else to fix it.
}

Chuwei Guo

**Comment by Tejas2Rangole** [comment]
Mechanical problem
