### ISSUE TITLE
Research a backup battery for the Dell

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#34]
Find a backup battery for the Dell DS we have this year. Look at the model number on the laptop and find the lowest cost battery available online.

**Comment by SourishMurthy1** [comment]
https://www.amazon.com/SE-Electronics-4-Cell-Battery-Latitude/dp/B01EPAAND4/ref=sr_1_6?ie=UTF8&qid=1485712298&sr=8-6&keywords=battery+for+dell+latitude+e7240
