### ISSUE TITLE
Organize the DS

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#37]
Using the Dell DS, look at the Smart Dashboard setup we have currently and organize it. If you can, come up with an organizational style to continue with in the future.

**Comment by nelsonfang117** [comment]
sup

**Comment by Knayam7** [comment]
Any progress guys?

**Comment by ScottSun42** [comment]
There's no Smart Dashboard in Dell right now

**Comment by ScottSun42** [comment]
Can't really organize what we don't currently have

**Comment by Knayam7** [comment]
Alright, I'm closing this for now. I want you guys to instead work on issue #42
