### ISSUE TITLE
Create a NavX Tester class

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#40]
Create a NavX Tester Class in utilities that displays the six axes to the SmartDashboard (three from gyro, three from accelerometer - we will most likely not be using the magnetometer)

**Comment by Tejas2Rangole** [comment]
Where is the documentation for ahrs?

**Comment by Knayam7** [comment]
http://www.kauailabs.com/public_files/navx-mxp/apidocs/java/
