### ISSUE TITLE
IMPORTANT MESSAGE: PLEASE COMMIT YOUR CODE

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#43]
Just a friendly reminder that if you've completed an issue, have someone look over your code, compile it to see if it works and then commit it using Github. Once you've done that, you can then close the issue being done

To clarify that you've seen this, please say "Excelsior" in the comment section below

Thanks,
Mayank

**Comment by kidlatmc29** [comment]
Excelsior

**Comment by gregoryquick** [comment]
But you told me to commit less... And what about using branches... And also this is non-coding; this is exactly the type of issue that label is for...

**Comment by Knayam7** [comment]
Dammit Gregory

**Comment by RockJia1** [comment]
Excelsior

**Comment by ScottSun42** [comment]
Excelsior

**Comment by NarrowUrchin** [comment]
Excelsior

**Comment by JedrekL** [comment]
elexsoire

**Comment by avigloz** [comment]
Excelspreadsheet

**Comment by djwadhwa** [comment]
Excelsior
