### ISSUE TITLE
Research Vision Tracking

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#44]
Look at vision tracking for our atu sequence heading forward. Talk to Gregory for more information.

**Comment by gregoryquick** [comment]
Library where I am working on testing: https://github.com/gregoryquick/VisionTest
Offline as of 15-09-2017

**Comment by gregoryquick** [comment]
Now getting and processing image, still need to get data out of processing thread...

**Comment by Knayam7** [comment]
You're making excellent progress Gregory

**Comment by gregoryquick** [comment]
Now getting and logging data from thread
