### ISSUE TITLE
Research motor controllers used in climber

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#46]
Go to systems and ask them what type of motor controller the climber will use. Also ask mech how long it will take for climber to be programmable

**Comment by JedrekL** [comment]
Only uses victors, total of 9. 
4 victors are used for drive.
1 victor used for lifter.
Other 4 and TBA (Probably ball shooting and collecting).

x amount of days for climber to be programmable.

[More on Speed Controllers](http://wpilib.screenstepslive.com/s/4485/m/13809/l/599702-driving-motors-with-speed-controller-objects-victors-talons-and-jaguars)
[Victors User Manual](https://content.vexrobotics.com/vexpro/pdf/217-2769-Victor888UserManual_20130118.pdf)
