### ISSUE TITLE
IMPORTANT MESSAGE: PLEASE DON'T FORGET TO SYNC

### ISSUE THREAD

**Issue by avigloz** [NRG948/NRGRobot2017#52]
This is really important. 
If you aren't synced, then work you do may be obsolete. In order to not waste time, please be aware of the need to sync before you start working on something, and sync before committing. 

If you've seen this, please comment "Rancho" down below

**Comment by Knayam7** [comment]
Rancho

**Comment by Miner12345** [comment]
Rancho

**Comment by Tejas2Rangole** [comment]
Ram Ranch
