### ISSUE TITLE
Calculate Measurements For Auto Movement

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#56]
Figure out the distances from each position (1, 2, and 3) to the corresponding gear lifts. Then comment what those distances are for each position. 

REFER TO THE GAME MANUAL FOR DISTANCES - https://firstfrc.blob.core.windows.net/frc2017/Manual/Sections/03-Arena.pdf

**Comment by Tejas2Rangole** [comment]
What is position 1,2 and 3?

**Comment by Knayam7** [comment]
Ask Reese

**Comment by gregoryquick** [comment]
And please put what the positions are on this issue when you ask Reese.

**Comment by Miner12345** [comment]
rancho

**Comment by kidlatmc29** [comment]
There are six positions. Red 1, Red 2, Red 3, Blue 1, Blue 2 and Blue 3. If you look at a map of the field, on the left side, Red 1 is the first position from the top of the map, then Red 2 is next position down, then finally Red 3 at the bottom of the map. On the right side, Blue 1 starts from the bottom, Blue 2 is the next position up, and Blue 3 is at the top of the map. 


If this is still confusing, I can just label a map. Tell me if you want a labeled map then.

**Comment by kidlatmc29** [comment]
![field map](https://cloud.githubusercontent.com/assets/16855448/22812687/1ddb0610-eefb-11e6-8673-fa803e9a1018.png)

Here's the map anyways ^

**Comment by Wolf110** [comment]
front hook to wall = 103.02"
blue/red gear lift facing boiler = 121.9"
blue/red gear lift facing audience = 121.9"
