### ISSUE TITLE
Download the FRC Driver Station Software (Urgent for leads)

### ISSUE THREAD

**Issue by chandrap2** [NRG948/NRGRobot2017#6]
The FRC Driver Station is used to enable the robot, check the robot status, configure the joysticks, and so on. After you push the code out to the robot from Eclipse, you open up the Driver Station program to enable the robot.
[This webpage has instructions and the download link.](https://wpilib.screenstepslive.com/s/4485/m/13503/l/599670-installing-the-frc-2016-update-suite-all-languages) At one point, the installer will give you a list of items from which you can choose what to install. **Install everything but the LabVIEW update.** The serial number is M82X13677. You'll also need to create a National Instruments account at the end.

**Comment by ChuweyBar** [comment]
Seriously tho, I don't think everyone need this.
