### ISSUE TITLE
Install a JRE on the new DS on competition bot

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#60]
Install a JRE on the new DS using the Java installation tool in the configs
Instructions here: http://wpilib.screenstepslive.com/s/4485/m/13503/l/599747-installing-java-8-on-the-roborio-using-the-frc-roborio-java-installer-java-only

**Comment by gregoryquick** [comment]
Is this installing the JRE on the laptop for the driver station or the roborio for the new robot?

**Comment by Knayam7** [comment]
Complete
